export { Home } from "./Home/Home";
export { Error404 } from "./404/Error404";
export { Products } from "./Products/Products";
export { WishList } from "./WishList/WishList";
export { Cart } from "./Cart/Cart";
export { SignUp } from "./SignUp/SignUp";
export { Login } from "./Login/Login";
export { MockmanPage } from "./Mockman";
export { Account } from "./Account/Account";
